name: bioinfo-env
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - nextflow>=23.04
  - bioconda::nanoplot>=1.42.0
  - python>=3.10
  - pip
  - pip:
    - numpy>=1.24
    - pandas>=2.0
    - matplotlib>=3.7
